server:
  port: 9095
spring:
  application:
     name: gateway-service

  cloud:
    gateway:
      routes:
       - id: product-service
         uri: http://localhost:9091
         predicates:
          - Path=/product/v1/**
         filters:
           - name: CircuitBreaker
             args:
               name: myCircuitBreaker
               fallbackUri: forward:/productServiceFallBack
       - id: order-service
         uri: http://localhost:9092
         predicates:
           - Path= /order/v1/**

resilience4j.circuitbreaker:
  configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        eventConsumerBufferSize: 10
resilience4j.timelimiter:
  configs:
    instances:
      timeoutDuration: 3s
      cancelRunningFuture: true
