server:
  port: 8787
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,configprops,metrics
spring:
  application:
     name: gateway-service

  cloud:
    gateway:
      routes:
       - id: customer-service
         uri: http://localhost:7070
         predicates:
           - Path= /user/v1/**

       - id: product-service
         uri: http://localhost:7071
         predicates:
          - Path=/product/v1/**
         filters:
           - name: CircuitBreaker
             args:
               name: myCircuitBreaker
               fallbackUri: forward:/productServiceFallBack

       - id: order-service
         uri: http://localhost:7072
         predicates:
           - Path= /order/v1/**
         filters:
           - name: CircuitBreaker
             args:
               name: myCircuitBreaker
               fallbackUri: forward:/orderServiceFallBack

       - id: payment-service
         uri: http://localhost:7073
         predicates:
           - Path= /payment/v1/**

resilience4j.circuitbreaker:
  configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        slidingWindowType: COUNT_BASED
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        eventConsumerBufferSize: 10
resilience4j.timelimiter:
  configs:
    instances:
      timeoutDuration: 3s
      cancelRunningFuture: true
