server:
  port: 9093
spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/e-payment
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      "default": http://localhost:8761/eureka