server:
  port: 7073
management:
  endpoints:
    web:
      exposure:
        include: info,health,env,configprops,metrics

spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/e-payment
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    showSql: true





eureka:
  client:
    serviceUrl:
      "default": http://localhost:8761/eureka