server:
  port: 7070
spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/e-user
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: nagarajujunna90@gmail.com
    password: xidd itss ugzj werm
    properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

