payment-service:
  url: http://host.docker.internal:7073/payment/v1
  create-payment: /payment/pay

management:
   endpoints:
       web:
        exposure:
          include: info,health,env,configprops,metrics
server:
  port: 7072
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/e-order
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update

eureka:
  client:
    serviceUrl:
      "default": http://localhost:8761/eureka



