server:
  port: 9091

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://host.docker.internal:3306/e-product
    username: root
    password: root
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true

eureka:
  client:
    serviceUrl:
      "default": http://localhost:8761/eureka

