server:
  port: 9091

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://employeedb.crmuy6se4h6v.us-east-1.rds.amazonaws.com:3306/e-product
    username: admin
    password: Prashanth1234
  jpa:
    hibernate:
      ddlAuto: update
    showSql: true

eureka:
  client:
    serviceUrl:
      "default": http://localhost:8761/eureka

