server:
  port: 9091

spring:
  profiles:
    active: local
  application:
    name: product-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: nagarajujunna90@gmail.com
    password: xidd itss ugzj werm
    properties:
      mail:
        smtp.auth: true
        starttls.enable: true

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      "default": http://localhost:8761/eureka
    enabled: false
    registerWithEureka: false


